import webpack from 'webpack';
import webpackDevMiddleWare from 'webpack-dev-middleware';

import config from '../../../webpack.config.dev.babel';
import initEnvVars from '../../../config'; // for environment variables

/**
 * Adds development addons to app
 * - Initializes Env Vars.
 * - Adds WebpackDevMiddleWare to compile client side React code
 * @typedef {{app: Express.Application}}
 * @param {Express.Application} app - generated by the function express()
 */
export default (app) => {
    // in development we have to initialize the local env variables ourselves
    initEnvVars();

    console.log('hello from dev add ons');

    const compiler = webpack(config);

    app.use(webpackDevMiddleWare(compiler, {
        noInfo: true,
        publicPath: config.output.publicPath,
    }));
};
